version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    environment:
    - MONGO_INITDB_ROOT_USERNAME=$ROOT_USER
    - MONGO_INITDB_ROOT_PASSWORD=$ROOT_PASS
    volumes:
      - ./mongodb-data:/data/db # persist db in a local folder
    ports:
    - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 5s
      timeout: 10s
      retries: 10
    restart: unless-stopped
  mongosetup:
    build:
      context: ./mongosetup
      args:
        - INIT_COLLECTION_URL=$INIT_COLLECTION_URL
    depends_on:
      mongodb:
        condition: service_healthy
    restart: "no"
    environment:
      - MONGO_USER=$ROOT_USER
      - MONGO_PASSWORD=$ROOT_PASS
      - MONGO_DB=airbnb
      - MONGO_COLLECTION=listingsAndReviews
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
    - ME_CONFIG_MONGODB_SERVER=mongodb
    - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    - ME_CONFIG_MONGODB_ADMINUSERNAME=$ROOT_USER
    - ME_CONFIG_MONGODB_ADMINPASSWORD=$ROOT_PASS
    - ME_CONFIG_BASICAUTH_USERNAME=$GUI_AUTH_USER
    - ME_CONFIG_BASICAUTH_PASSWORD=$GUI_AUTH_PASS
    depends_on:
    - mongodb
    ports:
    - 8081:8081
    healthcheck:
      test:  wget --quiet --tries=3 --spider http://$GUI_AUTH_USER:$GUI_AUTH_PASS@localhost:8081 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped