// This is the main JS file for all Algolia related logic. 
// InstantSearch is used, documentation root: https://www.algolia.com/doc/guides/building-search-ui/getting-started/js/
// This project was generated by the 'npx create-instantsearch-app' command as it appears on the configuration and modified later
export function init_algolia(appId, searchKey, indexName) {
    const { algoliasearch, instantsearch } = window;
    // Initialize the Algolia Search client and connect to our index
    const searchClient = algoliasearch(appId, searchKey);
    const search = instantsearch({
        indexName: indexName,
        routing: true,
        searchClient,
    });
    // If Algolia runs into an error, it's most likely an issue with AppId/SearchKey/IndexName. Redirect back to setup
    search.addListener('error', function () { 
        showSetup('Algolia failed to initialize, parameters are not configured correctly.')
    })
    
    // Define custom logic that runs when the results changed.
    // This will call a function that displays the total result count and allows the user to Load more or clear filters if needed.
    // The hitsChanged method is defined below to keep the initialization code clean.
    // Documentation: https://www.algolia.com/doc/api-reference/widgets/infinite-hits/js/
    const renderInfiniteHits = hitsChanged;
    const customInfiniteHits = instantsearch.connectors.connectInfiniteHits(
        renderInfiniteHits
    );

    // The main logic for Algolia initialization, this initializes all the widgets we use
    search.addWidgets([
        // Add a Search Box to our page. Documentation: https://www.algolia.com/doc/api-reference/widgets/search-box/js/
        instantsearch.widgets.searchBox({
            container: '#searchbox',
            placeholder: 'Search real-estate listings',
            autofocus: true
        }),
        // We use InfiniteHits instead of the default 'Hits' widget, to enable infinite scrolling, which suits our usecase better
        // Documentation: https://www.algolia.com/doc/api-reference/widgets/infinite-hits/js/
        instantsearch.widgets.infiniteHits({
            container: '#hits',
            templates: {
                // We use no 'empty' template, as our results container will be hidden if there are no results.
                // The item template is heavily modified to draw the details of a listing in detail
                item: `
<article id="hit-{{objectID}}">
  
  <div class="name-container">
    <h1 class="name">{{#helpers.highlight}}{ "attribute": "name" }{{/helpers.highlight}}</h1>
    {{#scores}}
    <div class="stars">
      <svg aria-hidden="true"> 
      {{#scores.has_one}}
        <use xlink:href="#ais-RatingMenu-starSymbol"></use>
      {{/scores.has_one}}
      {{^scores.has_one}}
        <use xlink:href="#ais-RatingMenu-starEmptySymbol"></use>
      {{/scores.has_one}}
       </svg>
       <svg aria-hidden="true"> 
      {{#scores.has_two}}
        <use xlink:href="#ais-RatingMenu-starSymbol"></use>
      {{/scores.has_two}}
      {{^scores.has_two}}
        <use xlink:href="#ais-RatingMenu-starEmptySymbol"></use>
      {{/scores.has_two}}
       </svg>
       <svg aria-hidden="true"> 
       {{#scores.has_three}}
         <use xlink:href="#ais-RatingMenu-starSymbol"></use>
       {{/scores.has_three}}
       {{^scores.has_three}}
         <use xlink:href="#ais-RatingMenu-starEmptySymbol"></use>
       {{/scores.has_three}}
        </svg>
        <svg aria-hidden="true"> 
        {{#scores.has_four}}
          <use xlink:href="#ais-RatingMenu-starSymbol"></use>
        {{/scores.has_four}}
        {{^scores.has_four}}
          <use xlink:href="#ais-RatingMenu-starEmptySymbol"></use>
        {{/scores.has_four}}
         </svg>
         <svg aria-hidden="true"> 
         {{#scores.has_five}}
           <use xlink:href="#ais-RatingMenu-starSymbol"></use>
         {{/scores.has_five}}
         {{^scores.has_five}}
           <use xlink:href="#ais-RatingMenu-starEmptySymbol"></use>
         {{/scores.has_five}}
          </svg>
    </div>
    {{/scores}}
  </div>
  {{#description}}
  <div class="description">
      <div class="title">Description{{}}</div>
      <p class="desc">{{#helpers.highlight}}{ "attribute": "description" }{{/helpers.highlight}}</p>
  </div>
  {{/description}}
  {{#summary}}
  <div class="summary">
      <div class="title">Summary</div>
      <p class="desc">{{#helpers.highlight}}{ "attribute": "summary" }{{/helpers.highlight}}</p>
  </div>
  {{/summary}}
  {{#space}}
  <div class="space">
      <div class="title">Space</div>
      <p class="desc">{{#helpers.highlight}}{ "attribute": "space" }{{/helpers.highlight}}</p>
  </div>
  {{/space}}
  {{#neighborhood}}
  <div class="neigh">
      <div class="title">Neighborhood</div>
      <p class="desc">{{#helpers.highlight}}{ "attribute": "neighborhood_overview" }{{/helpers.highlight}}</p>
  </div>
  {{/neighborhood}}
  {{#transit}}
  <div class="transit">
      <div class="title">Transit</div>
      <p class="desc">{{#helpers.highlight}}{ "attribute": "transit" }{{/helpers.highlight}}</p>
  </div>
  {{/transit}}
 
  <div class="info">
    {{#property_type}}
        <div>
            <span class="title">Property Type:</span>
            <span>{{property_type}}</span>
        </div>
    {{/property_type}}
    {{#address}}
      <div>
        <span class="title">Address:</span>
        <span>{{#helpers.highlight}}{ "attribute": "address.street" }{{/helpers.highlight}}</span>
      </div>
      {{/address}}
      {{#price}}
      <div>
        <span class="title">Price:</span>
        <b>{{price}}$ per night</b>
        {{#cleaning_fee}}
        <span> + {{cleaning_fee}}$ cleaning fee</span>
        {{/cleaning_fee}}
        {{#security_deposit}}
        <span> + {{security_deposit}}$ security deposit</span>
        {{/security_deposit}}
      </div>
      {{/price}}
      {{#accommodates}}
      <div>
        <span class="title">Accommodates:</span>
        <b>{{accommodates}} people</b>
        {{#bedrooms}}
        <span> in {{bedrooms}} bedroom(s)</span>
        {{/bedrooms}}
        {{#beds}}
        <span>, {{beds}} bed(s)</span>
        {{/beds}}
        {{#bathrooms}}
        <span> with {{bathrooms}} bathroom(s)</span>
        {{/bathrooms}}
       </div>
      {{/accommodates}}
  </div>
 
  {{#images.picture_url}}
  <img class="image" src="{{images.picture_url}}">
  {{/images.picture_url}}
</article>
`
        },
        }),
        // We configure a widget to allow users to specify the number of items to be loaded at a time
        // Documentation: https://www.algolia.com/doc/api-reference/widgets/hits-per-page/js/
        instantsearch.widgets.hitsPerPage({
            container: '#per-page',
            items: [
                { label: 'Load 5 results per page', value: 5 },
                { label: 'Load 10 results per page', value: 10 },
                { label: 'Load 20 results per page', value: 20 },
                { label: 'Load 50 results per page', value: 50, default: true },
                { label: 'Load 100 results per page', value: 100 },
                { label: 'Load 200 results per page', value: 200 }

            ]
        }),
        // We add a Clear Refinements button to filters, and call it 'Clear filters'
        // Documentation: https://www.algolia.com/doc/api-reference/widgets/clear-refinements/js/
        instantsearch.widgets.clearRefinements({
            container: '#clear-refinements',
            templates: {
                resetLabel: 'Clear filters',
            },
        }),
        // We add  Refinement lists for Property Type and Country on our filter bar
        // Documentation: https://www.algolia.com/doc/api-reference/widgets/refinement-list/js/
        instantsearch.widgets.refinementList({
            container: '#property-list',
            attribute: 'property_type'
        }),
        instantsearch.widgets.refinementList({
            container: '#country-list',
            attribute: 'address.country'
        }),
        // We add a rating menu, so results can be filtered by ratings
        // Documentation: https://www.algolia.com/doc/api-reference/widgets/rating-menu/js/
        instantsearch.widgets.ratingMenu({
            container: '#review-scores',
            attribute: 'scores.stars'
        }),
        // We add range sliders for Price and Cleaning Fee
        // https://www.algolia.com/doc/api-reference/widgets/range-slider/js/
        instantsearch.widgets.rangeSlider({
            container: '#price',
            attribute: 'price',
            precision: 10
        }),
        instantsearch.widgets.rangeSlider({
            container: '#cleaning-fee',
            attribute: 'cleaning_fee',
            precision: 5
        }),
        // We add a Map (Google Map engine) to enable Geo searching in a selected area
        // https://www.algolia.com/doc/api-reference/widgets/geo-search/js/
        instantsearch.widgets.geoSearch({
            container: '#geo-search',
            googleReference: window.google,
            initialPosition: {
                lat: 48.864716,
                lng: 2.349014,
            },
            initialZoom: 10,
            builtInMarker: {
                createOptions(item) {
                    return {
                        title: item.name,
                    };
                },
                events: {
                    click({ event, item, marker, map }) {
                        // When a marker is clicked, we scroll to the selected listing
                        document.getElementById('hit-' + item.objectID).scrollIntoView({ behavior: "smooth", block: "end", inline: "nearest" });
                    },
                },
            },
        }),
        // We add our own widget, which is defined above.
        // This will call the 'hitsChanged' method below every time the result set changes.
        customInfiniteHits({

        })

    ]);

    // This function is called every time the search results change
    // It checks how many results there are in total and either:
    // - displays a 'No results found' message to the user along with the possibility to Clear Filters. It also hides the result container and possibly the map too
    // - displays information about how many total results there are, and how many are currently displayed. It also allows the users to click a 'Load more' button on the top of the page.
    function hitsChanged(renderOptions) {

        // if this is an initial render and we got no results object, skip
        if (!renderOptions.results) {
            return;
        }
        // get the reference for the Result Count elements on the UI (its text and link as well)
        const resultCountElement = document.getElementById('result-count');
        const textEl = resultCountElement.querySelector('span');
        const linkEl = resultCountElement.querySelector('a');
        // check if we have any results
        const hasHits = renderOptions.results.nbHits !== 0;
        // check if we have any search query
        const hasQuery = !!renderOptions.results.query;
        // check if we have any geo bounding box (query made on map)
        const hasGeoQuery = !!renderOptions.results._state.insideBoundingBox;

        // We show/hide result Details depending if we have results or not
        document.getElementById('details-display').style.display = hasHits ? 'block' : 'none';
        // We hide the Map display if we have no results AND there was no map query applied (so the query can be undone)
        document.getElementById('map-display').style.display = hasHits || hasGeoQuery ? 'block' : 'none';
        // Update the Result count container to display information about results
        if (hasHits) {
            // if there are any results
            if (renderOptions.isLastPage) {
                // if we are on last page, show text and a link to clear filters
                textEl.innerText = `Showing all ${renderOptions.hits.length} results`;
                linkEl.style.display = 'none';
                linkEl.innerText = 'Clear all filters';
                linkEl.href = '.';
                linkEl.style.display = 'inline';
                linkEl.onclick = null;
            } else {
                // if we are not on last page, show text and link to load more items
                textEl.innerText = `Showing top ${renderOptions.hits.length} results of ${renderOptions.results.nbHits}`;
                linkEl.href = '';
                linkEl.innerText = 'Load more';
                linkEl.style.display = 'inline';
                linkEl.href = "#";
                linkEl.onclick = () => {
                    renderOptions.showMore();
                    return false;
                };
            }
        } else {
            // if we have no results, construct message
            let statusMessage = 'No results have been found';
            if (hasQuery) {
                statusMessage += ` for '${renderOptions.results.query}'`;
            }
            if (hasGeoQuery) {
                statusMessage += ' in selected map area';
            }
            // show message and link to clear filters
            textEl.innerText = statusMessage
            linkEl.innerText = 'Clear all filters';
            linkEl.href = '.';
            linkEl.style.display = 'inline';
            linkEl.onclick = null;
        }
    }
        

    search.start();

}